# Generated by Django 5.1.4 on 2024-12-29 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
